name: exampleSwiftUIApp 
options:
  bundleIdPrefix: com.zggff

packages:
  Inject:
    url: https://github.com/krzysztofzablocki/Inject.git
    from: 1.2.4
  InjectionNext:
    url: https://github.com/johnno1962/InjectionNext.git
    from: 2.0.0


targets:
  ExampleUIKitApp:
    type: application
    platform: [iOS, macOS]
    deploymentTarget: "16.0"
    sources: [Sources]
    dependencies:
      - package: Inject
      - package: InjectionNext
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
      configs:
        Debug:
          OTHER_LDFLAGS: "$(inherited) -Xlinker -interposable"
          EMIT_FRONTEND_COMMAND_LINES: "YES"

